# Generated by Django 2.2.8 on 2019-12-15 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Teacher'), (2, 'Student'), (3, 'Parent')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('admission_no', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='pictures/')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Grade_one'), (2, 'Grade_two'), (3, 'Grade_three'), (4, 'Grade_four'), (5, 'Grade_five'), (6, 'Grade_six'), (7, 'Grade_seven'), (8, 'Grade_eight')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('term_1', models.CharField(max_length=5)),
                ('term_2', models.CharField(max_length=5)),
                ('tem_3', models.CharField(max_length=5)),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_school.StudentProfile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_school.TeacherProfile')),
            ],
        ),
    ]
