# Generated by Django 2.2.8 on 2019-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_school', '0002_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(default='images/blur.jpeg', upload_to='images/'),
        ),
    ]
